(require 'cl-lib)
(defconst giv-keywords '(offset tab-width  indent-level indent-spaces padding)
  "")
(defun giv-guess (&optional major-mode-prefix)
  (let* ((major-mode-prefix (or major-mode-prefix (replace-regexp-in-string "-mode$" "" (symbol-name major-mode))))
         (regexps (mapcar (lambda (keyword)
                            (format "^%s-.*%s$" major-mode-prefix keyword))
                          giv-keywords))
         (indent-variable-p-fn (lambda (symbol)
                                 (cl-some (lambda (regexp)
                                            (string-match-p regexp (symbol-name symbol)))
                                          regexps)))
         (indent-variables))
    (mapatoms (lambda (symbol)
                (when (funcall indent-variable-p-fn symbol)
                  (push symbol indent-variables))))
    indent-variables))

(provide 'guess-indent-variables)
